// <auto-generated />
using System;
using CMSECommerce.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMSECommerce.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260211185359_ReseedCorrectedUsersFinal")]
    partial class ReseedCorrectedUsersFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMSECommerce.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("CMSECommerce.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActionMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Controller")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CMSECommerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 0,
                            Name = "Shirts",
                            Slug = "shirts"
                        },
                        new
                        {
                            Id = 2,
                            Level = 0,
                            Name = "Fruit",
                            Slug = "fruit"
                        },
                        new
                        {
                            Id = 3,
                            Level = 1,
                            Name = "T-Shirts",
                            ParentId = 1,
                            Slug = "t-shirts"
                        },
                        new
                        {
                            Id = 4,
                            Level = 1,
                            Name = "Formal Shirts",
                            ParentId = 1,
                            Slug = "formal-shirts"
                        },
                        new
                        {
                            Id = 5,
                            Level = 1,
                            Name = "Apples",
                            ParentId = 2,
                            Slug = "apples"
                        },
                        new
                        {
                            Id = 6,
                            Level = 1,
                            Name = "Oranges",
                            ParentId = 2,
                            Slug = "oranges"
                        });
                });

            modelBuilder.Entity("CMSECommerce.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId", "IsRead");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("CMSECommerce.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Shipped")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CMSECommerce.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CancelledByRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReturnReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellerNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("CMSECommerce.Models.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "This is the home page",
                            Order = 0,
                            Slug = "home",
                            Title = "Home"
                        },
                        new
                        {
                            Id = 2,
                            Body = "This is the about page",
                            Order = 0,
                            Slug = "about",
                            Title = "About"
                        },
                        new
                        {
                            Id = 3,
                            Body = "This is the services page",
                            Order = 0,
                            Slug = "services",
                            Title = "Services"
                        },
                        new
                        {
                            Id = 4,
                            Body = "This is the contact page",
                            Order = 0,
                            Slug = "contact",
                            Title = "Contact"
                        });
                });

            modelBuilder.Entity("CMSECommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Juicy apples",
                            Image = "apple1.jpg",
                            IsVisible = true,
                            Name = "Apples",
                            OwnerName = "Admin",
                            Price = 1.50m,
                            Slug = "apples",
                            Status = 1,
                            StockQuantity = 100,
                            StoreId = 1,
                            UserId = "a18265d3-05b8-4766-adcc-ca43d3960199"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Juicy grapefruit",
                            Image = "grapefruit1.jpg",
                            IsVisible = true,
                            Name = "Grapefruit",
                            OwnerName = "Admin",
                            Price = 2m,
                            Slug = "grapefruit",
                            Status = 1,
                            StockQuantity = 100,
                            StoreId = 1,
                            UserId = "a18265d3-05b8-4766-adcc-ca43d3960199"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Fresh grapes",
                            Image = "grapes1.jpg",
                            IsVisible = true,
                            Name = "Grapes",
                            OwnerName = "Admin",
                            Price = 1.80m,
                            Slug = "grapes",
                            Status = 1,
                            StockQuantity = 100,
                            StoreId = 1,
                            UserId = "a18265d3-05b8-4766-adcc-ca43d3960199"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Fresh oranges",
                            Image = "orange1.jpg",
                            IsVisible = true,
                            Name = "Oranges",
                            OwnerName = "Admin",
                            Price = 1.50m,
                            Slug = "oranges",
                            Status = 1,
                            StockQuantity = 100,
                            StoreId = 1,
                            UserId = "a18265d3-05b8-4766-adcc-ca43d3960199"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Nice blue t-shirt",
                            Image = "blue1.jpg",
                            IsVisible = true,
                            Name = "Blue shirt",
                            OwnerName = "Admin",
                            Price = 7.99m,
                            Slug = "blue-shirt",
                            Status = 1,
                            StockQuantity = 100,
                            StoreId = 1,
                            UserId = "a18265d3-05b8-4766-adcc-ca43d3960199"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Nice red t-shirt",
                            Image = "red1.jpg",
                            IsVisible = true,
                            Name = "Red shirt",
                            OwnerName = "Admin",
                            Price = 8.99m,
                            Slug = "red-shirt",
                            Status = 1,
                            StockQuantity = 100,
                            StoreId = 1,
                            UserId = "a18265d3-05b8-4766-adcc-ca43d3960199"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Nice green t-shirt",
                            Image = "green1.png",
                            IsVisible = true,
                            Name = "Green shirt",
                            OwnerName = "Admin",
                            Price = 9.99m,
                            Slug = "green-shirt",
                            Status = 1,
                            StockQuantity = 100,
                            StoreId = 1,
                            UserId = "a18265d3-05b8-4766-adcc-ca43d3960199"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Nice pink t-shirt",
                            Image = "pink1.png",
                            IsVisible = true,
                            Name = "Pink shirt",
                            OwnerName = "Admin",
                            Price = 10.99m,
                            Slug = "pink-shirt",
                            Status = 1,
                            StockQuantity = 100,
                            StoreId = 1,
                            UserId = "a18265d3-05b8-4766-adcc-ca43d3960199"
                        });
                });

            modelBuilder.Entity("CMSECommerce.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CMSECommerce.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GSTIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Mumbai",
                            Contact = "0000000000",
                            Country = "India",
                            Email = "admin@local.local",
                            IsActive = true,
                            PostCode = "400001",
                            StoreName = "Admin Central Store",
                            UserId = "a18265d3-05b8-4766-adcc-ca43d3960199"
                        });
                });

            modelBuilder.Entity("CMSECommerce.Models.SubscriberRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscriberRequests");
                });

            modelBuilder.Entity("CMSECommerce.Models.SubscriptionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CreditApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsUpgrade")
                        .HasColumnType("bit");

                    b.Property<string>("ItsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TierId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TierId");

                    b.ToTable("SubscriptionRequests");
                });

            modelBuilder.Entity("CMSECommerce.Models.SubscriptionTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionTiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMonths = 1,
                            Name = "Trial",
                            Price = 99m,
                            ProductLimit = 5
                        },
                        new
                        {
                            Id = 2,
                            DurationMonths = 6,
                            Name = "Basic",
                            Price = 499m,
                            ProductLimit = 25
                        },
                        new
                        {
                            Id = 3,
                            DurationMonths = 12,
                            Name = "Intermediate",
                            Price = 899m,
                            ProductLimit = 50
                        },
                        new
                        {
                            Id = 4,
                            DurationMonths = 12,
                            Name = "Premium",
                            Price = 1499m,
                            ProductLimit = 120
                        });
                });

            modelBuilder.Entity("CMSECommerce.Models.UnlockRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnlockRequests", (string)null);
                });

            modelBuilder.Entity("CMSECommerce.Models.UserAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AgreementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAgreements");
                });

            modelBuilder.Entity("CMSECommerce.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentProductLimit")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentTierId")
                        .HasColumnType("int");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GpayQRCodePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ITSNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeactivated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImageApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImagePending")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProfileVisible")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PendingProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhonePeQRCodePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServicesProvided")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTierId");

                    b.HasIndex("ITSNumber")
                        .IsUnique();

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 107,
                            About = "Admin",
                            BusinessAddress = "Hyderabad",
                            CurrentProductLimit = 1000,
                            FirstName = "Weypaari",
                            HomeAddress = "Hyderabad",
                            ITSNumber = "100010",
                            IsDeactivated = false,
                            IsImageApproved = false,
                            IsImagePending = false,
                            IsProfileVisible = true,
                            LastName = "Admin",
                            Profession = "Admin",
                            UserId = "h07-8265d3-05b8-4766-adcc-ca43d3960197",
                            WhatsAppNumber = "9603302152"
                        },
                        new
                        {
                            Id = 1,
                            About = "Default System Administrator",
                            BusinessAddress = "Main Admin Office, Mumbai",
                            CurrentProductLimit = 1000,
                            FirstName = "System",
                            HomeAddress = "Default Admin Home",
                            ITSNumber = "000000",
                            IsDeactivated = false,
                            IsImageApproved = false,
                            IsImagePending = false,
                            IsProfileVisible = true,
                            LastName = "Admin",
                            Profession = "Administrator",
                            StoreId = 1,
                            SubscriptionStartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "a18265d3-05b8-4766-adcc-ca43d3960199",
                            WhatsAppNumber = "0000000000"
                        },
                        new
                        {
                            Id = 100,
                            About = "Admin",
                            BusinessAddress = "Hyderabad",
                            CurrentProductLimit = 1000,
                            FirstName = "Murtaza",
                            HomeAddress = "Hyderabad",
                            ITSNumber = "100001",
                            IsDeactivated = false,
                            IsImageApproved = false,
                            IsImagePending = false,
                            IsProfileVisible = true,
                            LastName = "Sagarwala",
                            Profession = "Admin",
                            UserId = "m01-8265d3-05b8-4766-adcc-ca43d3960191",
                            WhatsAppNumber = "9700081831"
                        },
                        new
                        {
                            Id = 101,
                            About = "Admin",
                            BusinessAddress = "Hyderabad",
                            CurrentProductLimit = 1000,
                            FirstName = "Abbas",
                            HomeAddress = "Hyderabad",
                            ITSNumber = "100002",
                            IsDeactivated = false,
                            IsImageApproved = false,
                            IsImagePending = false,
                            IsProfileVisible = true,
                            LastName = "Shajapurwala",
                            Profession = "Admin",
                            UserId = "a02-8265d3-05b8-4766-adcc-ca43d3960192",
                            WhatsAppNumber = "9963107763"
                        },
                        new
                        {
                            Id = 102,
                            About = "Admin",
                            BusinessAddress = "Hyderabad",
                            CurrentProductLimit = 1000,
                            FirstName = "Taher",
                            HomeAddress = "Hyderabad",
                            ITSNumber = "100003",
                            IsDeactivated = false,
                            IsImageApproved = false,
                            IsImagePending = false,
                            IsProfileVisible = true,
                            LastName = "Bensabwala",
                            Profession = "Admin",
                            UserId = "t03-8265d3-05b8-4766-adcc-ca43d3960193",
                            WhatsAppNumber = "8885216302"
                        },
                        new
                        {
                            Id = 103,
                            About = "Admin",
                            BusinessAddress = "Hyderabad",
                            CurrentProductLimit = 1000,
                            FirstName = "Taher",
                            HomeAddress = "Hyderabad",
                            ITSNumber = "100004",
                            IsDeactivated = false,
                            IsImageApproved = false,
                            IsImagePending = false,
                            IsProfileVisible = true,
                            LastName = "Hyderabadwala",
                            Profession = "Admin",
                            UserId = "t04-8265d3-05b8-4766-adcc-ca43d3960194",
                            WhatsAppNumber = "9849217820"
                        },
                        new
                        {
                            Id = 105,
                            About = "Admin",
                            BusinessAddress = "Hyderabad",
                            CurrentProductLimit = 1000,
                            FirstName = "Yahya",
                            HomeAddress = "Hyderabad",
                            ITSNumber = "100009",
                            IsDeactivated = false,
                            IsImageApproved = false,
                            IsImagePending = false,
                            IsProfileVisible = true,
                            LastName = "Aliasger",
                            Profession = "Admin",
                            UserId = "b72c9184-e4d2-4e5a-9391-7241065162a0",
                            WhatsAppNumber = "9130211052"
                        },
                        new
                        {
                            Id = 110,
                            About = "Admin",
                            BusinessAddress = "Hyderabad",
                            CurrentProductLimit = 1000,
                            FirstName = "Abdulqadir",
                            HomeAddress = "Hyderabad",
                            ITSNumber = "100011",
                            IsDeactivated = false,
                            IsImageApproved = false,
                            IsImagePending = false,
                            IsProfileVisible = true,
                            LastName = "Lokhandwala",
                            Profession = "Admin",
                            UserId = "ab05-8265d3-05b8-4766-adcc-ca43d3960101",
                            WhatsAppNumber = "9121835054"
                        },
                        new
                        {
                            Id = 111,
                            About = "Admin",
                            BusinessAddress = "Hyderabad",
                            CurrentProductLimit = 1000,
                            FirstName = "AL AQMAR",
                            HomeAddress = "Hyderabad",
                            ITSNumber = "100012",
                            IsDeactivated = false,
                            IsImageApproved = false,
                            IsImagePending = false,
                            IsProfileVisible = true,
                            LastName = "KANCHWALA",
                            Profession = "Admin",
                            UserId = "al08-8265d3-05b8-4766-adcc-ca43d3960102",
                            WhatsAppNumber = "9618443558"
                        },
                        new
                        {
                            Id = 112,
                            About = "Admin",
                            BusinessAddress = "Hyderabad",
                            CurrentProductLimit = 1000,
                            FirstName = "Abdul",
                            HomeAddress = "Hyderabad",
                            ITSNumber = "100013",
                            IsDeactivated = false,
                            IsImageApproved = false,
                            IsImagePending = false,
                            IsProfileVisible = true,
                            LastName = "Khader Patanwala",
                            Profession = "Admin",
                            UserId = "ak09-8265d3-05b8-4766-adcc-ca43d3960103",
                            WhatsAppNumber = "9949521090"
                        },
                        new
                        {
                            Id = 113,
                            About = "Admin",
                            BusinessAddress = "Hyderabad",
                            CurrentProductLimit = 1000,
                            FirstName = "Khuzaima",
                            HomeAddress = "Hyderabad",
                            ITSNumber = "100014",
                            IsDeactivated = false,
                            IsImageApproved = false,
                            IsImagePending = false,
                            IsProfileVisible = true,
                            LastName = "Saeed",
                            Profession = "Admin",
                            UserId = "kh10-8265d3-05b8-4766-adcc-ca43d3960104",
                            WhatsAppNumber = "9989664052"
                        });
                });

            modelBuilder.Entity("CMSECommerce.Models.UserStatusSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CleanupThresholdMinutes")
                        .HasColumnType("int");

                    b.Property<int>("OnlineThresholdMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserStatusSettings");
                });

            modelBuilder.Entity("CMSECommerce.Models.UserStatusTracker", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("UserStatuses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "5f90378b-3001-443b-8736-411a91341c2c",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "6f90378b-3001-443b-8736-411a91341c2d",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "7f90378b-3001-443b-8736-411a91341c2e",
                            Name = "Subscriber",
                            NormalizedName = "SUBSCRIBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "h07-8265d3-05b8-4766-adcc-ca43d3960197",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "h07-8265d3-05b8-4766-adcc-ca43d3960197",
                            Email = "weypaari@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "WEYPAARI@GMAIL.COM",
                            NormalizedUserName = "WEYPAARI@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOjDXAjLoCXb9ZOxNvGibbLlLwUPDvEH1+Gzdqym6UG+0Tuw2J38cFQaYZWc5cX38Q==",
                            PhoneNumber = "9603302152",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c07fd76f-e4de-6578-3bf8-423548845c13",
                            TwoFactorEnabled = false,
                            UserName = "weypaari@gmail.com"
                        },
                        new
                        {
                            Id = "a18265d3-05b8-4766-adcc-ca43d3960199",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a18265d3-05b8-4766-adcc-ca43d3960199",
                            Email = "admin@local.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCAL.LOCAL",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGl265m+rxZj1BUrcKVTfFs8PLZWIC73z4bdtPcid73FE82JHVEFI9hTJBF3vjKYtg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1840e320-7e7e-31c7-f6b2-291807391fc8",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "8e448304-2185-442e-a342-6e210168d87d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8e448304-2185-442e-a342-6e210168d87d",
                            Email = "hussaina@local.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "HUSSAINA@LOCAL.LOCAL",
                            NormalizedUserName = "HUSSAINA",
                            PasswordHash = "AQAAAAIAAYagAAAAEETlpxUk/VuI9w9EeAJL4vyZvG805WRA4kVDmWHbohjxT9Wx0hyar2Ba5ur7jNGlMw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ddcd9342-0bad-2c22-3198-510a21175506",
                            TwoFactorEnabled = false,
                            UserName = "hussaina"
                        },
                        new
                        {
                            Id = "m01-8265d3-05b8-4766-adcc-ca43d3960191",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "m01-8265d3-05b8-4766-adcc-ca43d3960191",
                            Email = "murtazahussain166@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MURTAZAHUSSAIN166@GMAIL.COM",
                            NormalizedUserName = "MURTAZAHUSSAIN166@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKIsXHjzP9dOg9KZ8M0NAMuKUuJgmO6SbLALGDaCmZ8ZpxsA04jmVn0lD2qgKNXnoQ==",
                            PhoneNumber = "9700081831",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "57b37af0-60a9-478a-ae26-86cd81ed7c27",
                            TwoFactorEnabled = false,
                            UserName = "murtazahussain166@gmail.com"
                        },
                        new
                        {
                            Id = "a02-8265d3-05b8-4766-adcc-ca43d3960192",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a02-8265d3-05b8-4766-adcc-ca43d3960192",
                            Email = "bharmalprojects@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BHARMALPROJECTS@GMAIL.COM",
                            NormalizedUserName = "BHARMALPROJECTS@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG7tQtAomf2wiNwWc9lserRueZ/jtdI+r/VDwv2xKhiXassWimo+T9njg4gjMPp4QQ==",
                            PhoneNumber = "9963107763",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8c6cdeef-d708-9ad2-479a-02c60a8086b3",
                            TwoFactorEnabled = false,
                            UserName = "bharmalprojects@gmail.com"
                        },
                        new
                        {
                            Id = "t03-8265d3-05b8-4766-adcc-ca43d3960193",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "t03-8265d3-05b8-4766-adcc-ca43d3960193",
                            Email = "mailbox.taher@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MAILBOX.TAHER@GMAIL.COM",
                            NormalizedUserName = "MAILBOX.TAHER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG5DgcJP1kUUEEcKRHPXBDtvf0gORLQMmXc1YSqiYZarfKwKUNbght/qLp2WOjj06A==",
                            PhoneNumber = "8885216302",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b651f1d9-b39f-25ec-1788-67530ec34d56",
                            TwoFactorEnabled = false,
                            UserName = "mailbox.taher@gmail.com"
                        },
                        new
                        {
                            Id = "t04-8265d3-05b8-4766-adcc-ca43d3960194",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "t04-8265d3-05b8-4766-adcc-ca43d3960194",
                            Email = "thussain98490@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "THUSSAIN98490@GMAIL.COM",
                            NormalizedUserName = "THUSSAIN98490@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECPCzvlkHtnVSN8sZun6Ty+n51Lz4q2a8cWowSFWikdfwj/i0b8GF5chrFz4BIpDRA==",
                            PhoneNumber = "9849217820",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "531979be-47fa-a133-ae4b-ca858da22655",
                            TwoFactorEnabled = false,
                            UserName = "thussain98490@gmail.com"
                        },
                        new
                        {
                            Id = "b72c9184-e4d2-4e5a-9391-7241065162a0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b72c9184-e4d2-4e5a-9391-7241065162a0",
                            Email = "yaliasger@yahoo.co.in",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "YALIASGER@YAHOO.CO.IN",
                            NormalizedUserName = "YALIASGER@YAHOO.CO.IN",
                            PasswordHash = "AQAAAAIAAYagAAAAEHjtA4Zlh2sWN8GPVzoBix9/Zbm7Tx7125vmzAHTQwf4D3ewNVrleQ9oOQWaZz1Ywg==",
                            PhoneNumber = "9130211052",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "868c12ff-161a-73f1-97dd-b9283583441c",
                            TwoFactorEnabled = false,
                            UserName = "yaliasger@yahoo.co.in"
                        },
                        new
                        {
                            Id = "ab05-8265d3-05b8-4766-adcc-ca43d3960101",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ab05-8265d3-05b8-4766-adcc-ca43d3960101",
                            Email = "abdulqadirlokhandwalaandwala@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ABDULQADIRLOKHANDWALAANDWALA@GMAIL.COM",
                            NormalizedUserName = "ABDULQADIRLOKHANDWALAANDWALA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPxIXt4kddK2gXpFvEhEmq6K/puWnvzew0pYJqlISDGX+kroTw5Hye4sogMh3INd/A==",
                            PhoneNumber = "9121835054",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e4ed174e-5570-fec3-a35b-9ace342637c7",
                            TwoFactorEnabled = false,
                            UserName = "abdulqadirlokhandwalaandwala@gmail.com"
                        },
                        new
                        {
                            Id = "al08-8265d3-05b8-4766-adcc-ca43d3960102",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "al08-8265d3-05b8-4766-adcc-ca43d3960102",
                            Email = "alaqmarak0810@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALAQMARAK0810@GMAIL.COM",
                            NormalizedUserName = "ALAQMARAK0810@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHrFyl25AgN+uQdViRnKGMqLxxo7IYcGkjMnYQUP07zwQqmloZbMHWxpYyoQ/mW/eg==",
                            PhoneNumber = "9618443558",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9e3226c9-7e1e-488b-ee65-cb487dc7b5ba",
                            TwoFactorEnabled = false,
                            UserName = "alaqmarak0810@gmail.com"
                        },
                        new
                        {
                            Id = "ak09-8265d3-05b8-4766-adcc-ca43d3960103",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ak09-8265d3-05b8-4766-adcc-ca43d3960103",
                            Email = "akframes@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "AKFRAMES@GMAIL.COM",
                            NormalizedUserName = "AKFRAMES@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIxE7niJWrgmrwE9D1iqDv3z8Dc4xDPtJz+BcALSMPqHitfdF2U5c2zZ0qS5dr+NaA==",
                            PhoneNumber = "9949521090",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "566a6d6b-ea65-a481-5f9d-6adbccda0222",
                            TwoFactorEnabled = false,
                            UserName = "akframes@gmail.com"
                        },
                        new
                        {
                            Id = "kh10-8265d3-05b8-4766-adcc-ca43d3960104",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "kh10-8265d3-05b8-4766-adcc-ca43d3960104",
                            Email = "Mohdkhuzaima@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MOHDKHUZAIMA@GMAIL.COM",
                            NormalizedUserName = "MOHDKHUZAIMA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL+FS7wy1wqTWVqwUtf3o1HW8Rmr4pgZ9n+pelf44+qJ3U2DRDc/sQsVto1aMtLBfg==",
                            PhoneNumber = "9989664052",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c48607b7-474c-e30d-f8b6-b3d6f76445f1",
                            TwoFactorEnabled = false,
                            UserName = "Mohdkhuzaima@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "h07-8265d3-05b8-4766-adcc-ca43d3960197",
                            RoleId = "5f90378b-3001-443b-8736-411a91341c2c"
                        },
                        new
                        {
                            UserId = "a18265d3-05b8-4766-adcc-ca43d3960199",
                            RoleId = "5f90378b-3001-443b-8736-411a91341c2c"
                        },
                        new
                        {
                            UserId = "8e448304-2185-442e-a342-6e210168d87d",
                            RoleId = "5f90378b-3001-443b-8736-411a91341c2c"
                        },
                        new
                        {
                            UserId = "m01-8265d3-05b8-4766-adcc-ca43d3960191",
                            RoleId = "5f90378b-3001-443b-8736-411a91341c2c"
                        },
                        new
                        {
                            UserId = "a02-8265d3-05b8-4766-adcc-ca43d3960192",
                            RoleId = "5f90378b-3001-443b-8736-411a91341c2c"
                        },
                        new
                        {
                            UserId = "t03-8265d3-05b8-4766-adcc-ca43d3960193",
                            RoleId = "5f90378b-3001-443b-8736-411a91341c2c"
                        },
                        new
                        {
                            UserId = "t04-8265d3-05b8-4766-adcc-ca43d3960194",
                            RoleId = "5f90378b-3001-443b-8736-411a91341c2c"
                        },
                        new
                        {
                            UserId = "b72c9184-e4d2-4e5a-9391-7241065162a0",
                            RoleId = "5f90378b-3001-443b-8736-411a91341c2c"
                        },
                        new
                        {
                            UserId = "ab05-8265d3-05b8-4766-adcc-ca43d3960101",
                            RoleId = "5f90378b-3001-443b-8736-411a91341c2c"
                        },
                        new
                        {
                            UserId = "al08-8265d3-05b8-4766-adcc-ca43d3960102",
                            RoleId = "5f90378b-3001-443b-8736-411a91341c2c"
                        },
                        new
                        {
                            UserId = "ak09-8265d3-05b8-4766-adcc-ca43d3960103",
                            RoleId = "5f90378b-3001-443b-8736-411a91341c2c"
                        },
                        new
                        {
                            UserId = "kh10-8265d3-05b8-4766-adcc-ca43d3960104",
                            RoleId = "5f90378b-3001-443b-8736-411a91341c2c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CMSECommerce.Models.AuditLog", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CMSECommerce.Models.Category", b =>
                {
                    b.HasOne("CMSECommerce.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CMSECommerce.Models.OrderDetail", b =>
                {
                    b.HasOne("CMSECommerce.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CMSECommerce.Models.Product", b =>
                {
                    b.HasOne("CMSECommerce.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMSECommerce.Models.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CMSECommerce.Models.Review", b =>
                {
                    b.HasOne("CMSECommerce.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CMSECommerce.Models.Store", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CMSECommerce.Models.SubscriptionRequest", b =>
                {
                    b.HasOne("CMSECommerce.Models.SubscriptionTier", "Tier")
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("CMSECommerce.Models.UserAgreement", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CMSECommerce.Models.UserProfile", b =>
                {
                    b.HasOne("CMSECommerce.Models.SubscriptionTier", "CurrentTier")
                        .WithMany()
                        .HasForeignKey("CurrentTierId");

                    b.HasOne("CMSECommerce.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithOne()
                        .HasForeignKey("CMSECommerce.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CurrentTier");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMSECommerce.Models.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("CMSECommerce.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("CMSECommerce.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CMSECommerce.Models.Store", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
